---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/base/istio-system"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system-istio-base
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  path: "./k8s/namespaces/base/istio-system/istio-base"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: istio-system-namespace
      namespace: flux-system
---
# TODO: Unusable with Talos until the fix PR is merged: https://github.com/istio/istio/issues/38794
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: istio-system-istio-cni
#   namespace: flux-system
# spec:
#   interval: 5m
#   timeout: 10m
#   path: "./k8s/namespaces/base/istio-system/istio-cni"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   dependsOn:
#     - name: istio-system-istio-base
#       namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system-istiod
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  path: "./k8s/namespaces/base/istio-system/istiod"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # dependsOn:
  #   - name: istio-system-istio-cni
  #     namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system-flagger
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  path: "./k8s/namespaces/base/istio-system/flagger"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: istio-system-istiod
      namespace: flux-system
