---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-ingress-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/base/istio-ingress"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-ingress-istio-gateway
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/base/istio-ingress/istio-gateway"
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: istio-system-istiod
      namespace: flux-system
  # patches:
  #   - patch: |-
  #       apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #       kind: HelmRelease
  #       metadata:
  #         name: istio-gateway
  #         namespace: istio-ingress
  #       spec:
  #         values:
  #           service:
  #             annotations:
  #               cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "neg-1-80"}}}'
