---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monkey-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/base/monkey"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monkey-monkey-app
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  path: "./k8s/namespaces/base/monkey/monkey-app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: monkey-namespace
      namespace: flux-system
