---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: hackathon.2022.1@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: michaelfornaro@gmail.com
            apiTokenSecretRef:
              name: cloudflare-cert-manager-token
              key: api-token

    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: rising-capsule-353505
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
