---
# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: k8s/clusters/.*
    encrypted_regex: ^(data|stringData)$
    gcp_kms: projects/rising-capsule-353505/locations/global/keyRings/sops/cryptoKeys/sops-key
