---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      version: 1.13.3
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: true
  valuesFrom:
  - kind: ConfigMap
    name: istio-gateway-config
