---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monkey-app
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: '*.chaosmonkeys.net'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monkey
                port:
                  number: 7777
