---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monkey-app
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    # cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  rules:
    - host: app.chaosmonkeys.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monkey
                port:
                  number: 7777
