apiVersion: v1
kind: Service
metadata:
  name: monkey
spec:
  selector:
    app: monkey
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 8080
      name: http-web
      appProtocol: http
