# Template examples https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/templates/cluster-template.yaml
---
## Cluster configs

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      # Match defaults from Talos setup https://www.talos.dev/v1.0/reference/configuration/#clusternetworkconfig
      cidrBlocks: ["10.244.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPCluster
    name: ${CLUSTER_NAME}
  controlPlaneRef:
    kind: TalosControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: ${CLUSTER_NAME}-controlplane
---
# https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/api/v1beta1/gcpcluster_types.go
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  project: ${GCP_PROJECT}
  region: ${GCP_REGION}
  network:
    name: ${GCP_NETWORK}
---
## Control plane configs

apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: ${CLUSTER_NAME}-controlplane
spec:
  version: v${KUBERNETES_VERSION}
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  infrastructureTemplate:
    kind: GCPMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: ${CLUSTER_NAME}-controlplane
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: ${TALOS_VERSION}
    init:
      generateType: init
      configPatches:
        - op: replace
          path: /cluster/proxy/disabled
          value: true
        - op: replace
          path: /cluster/network/cni
          value:
            name: none
---
kind: GCPMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: ${CLUSTER_NAME}-controlplane
spec:
  template:
    spec:
      instanceType: ${GCP_CONTROL_PLANE_MACHINE_TYPE}
      image: ${GCP_CONTROL_PLANE_IMAGE_ID}
      publicIP: true
      rootDeviceSize: ${GCP_CONTROL_PLANE_VOL_SIZE}
      serviceAccounts:
        email: ${GCP_VM_SVC_ACCOUNT}
        scopes:
          - "https://www.googleapis.com/auth/compute"
---
## Worker configs

apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
    nodepool: nodepool-a
  name: ${CLUSTER_NAME}-workers
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
      nodepool: nodepool-a
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
        nodepool: nodepool-a
    spec:
      clusterName: ${CLUSTER_NAME}
      failureDomain: ${GCP_REGION}-a
      version: ${KUBERNETES_VERSION}
      bootstrap:
        configRef:
          name: ${CLUSTER_NAME}-workers
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
      infrastructureRef:
        name: ${CLUSTER_NAME}-workers
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPMachineTemplate
  revisionHistoryLimit: 1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-workers
spec:
  template:
    spec:
      instanceType: ${GCP_NODE_MACHINE_TYPE}
      image: ${GCP_NODE_IMAGE_ID}
      serviceAccounts:
        email: ${GCP_VM_SVC_ACCOUNT}
        scopes:
          - "https://www.googleapis.com/auth/compute"
      publicIP: true
      rootDeviceSize: ${GCP_NODE_VOL_SIZE}
      # TODO: Investigate further; Preemptible defines if instance is preemptible
      # preemptible: false
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-workers
spec:
  template:
    spec:
      generateType: join
      talosVersion: ${TALOS_VERSION}
